version: "3"

services:
  thing-payloads-service-postgres-development:
    container_name: thing-payloads-service-postgres-development
    image: postgres:16.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=thing_payloads
